services:
  app:
    image: zodern/meteor
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/carpool
      - PORT=3000
    volumes:
      - ./build/app.tar.gz:/bundle/bundle.tar.gz
    depends_on:
      - mongo
      - tileserver-gl
      - nominatim
    restart: unless-stopped
    networks:
      - carpool_network

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    networks:
      - carpool_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=carpool
    depends_on:
      - mongo
    restart: unless-stopped
    profiles: ["manual"]
    networks:
      - carpool_network

  tileserver-gl:
    image: "maptiler/tileserver-gl:latest"
    container_name: tileserver-gl
    command:
      - --port
      - "8082"
      - --config
      - "/style/config.json"
    volumes:
      - ./openmaptilesdata/data:/data
      - ./openmaptilesdata/style:/style
      - ./openmaptilesdata/build:/build
    restart: unless-stopped
    networks:
      - carpool_network

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:5.1
    environment:
      - PBF_PATH=/nominatim/data/north-america/canada/british-columbia.osm.pbf
    volumes:
      - ./openmaptilesdata/data:/nominatim/data
      - ./pgdataNominatimInternal:/var/lib/postgresql/16/main
    restart: unless-stopped
    networks:
      - carpool_network

  service-proxy:
    image: nginx:alpine
    container_name: service-proxy
    ports:
      - "8080:8080"  # Nominatim
      - "8082:8082"  # Tileserver
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tileserver-gl
      - nominatim
    restart: unless-stopped
    networks:
      - carpool_network

networks:
  carpool_network:
    driver: bridge
