services:
  app:
    image: zodern/meteor
    container_name: carpool-app
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/carpool
      - PORT=3000
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "meteor npm install && meteor run --production"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: carpool-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
