services:
  app:
    image: zodern/meteor
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/carpool
      - PORT=3000
    volumes:
      - ./build/app.tar.gz:/bundle/bundle.tar.gz
    depends_on:
      mongo:
        condition: service_healthy
      tileserver-gl:
        condition: service_healthy
      nominatim:
        condition: service_healthy
      osrm:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - carpool_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--show-error", "--output", "/dev/null", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 600s

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    networks:
      - carpool_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=carpool
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["manual"]
    networks:
      - carpool_network

  tileserver-gl:
    image: "maptiler/tileserver-gl:latest"
    container_name: tileserver-gl
    command:
      - --port
      - "8082"
      - --config
      - "/style/config.json"
    volumes:
      - ./openmaptilesdata/data:/data
      - ./openmaptilesdata/style:/style
      - ./openmaptilesdata/build:/build
    restart: unless-stopped
    networks:
      - carpool_network
    healthcheck:
      test:
        ["CMD", "node", "-e", "require('net').connect({host: '127.0.0.1', port: 8082}).on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:5.1
    environment:
      - PBF_PATH=/nominatim/data/north-america/canada/british-columbia.osm.pbf
    volumes:
      - ./openmaptilesdata/data:/nominatim/data
      - ./pgdataNominatimInternal:/var/lib/postgresql/16/main
    restart: unless-stopped
    networks:
      - carpool_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--show-error", "--output", "/dev/null", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  osrm:
    container_name: osrm
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/british-columbia.osrm --port 8083
    volumes:
      - ./osrmdata/data:/data
    restart: unless-stopped
    networks:
      - carpool_network
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 127.0.0.1 8083"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  service-proxy:
    image: nginx:alpine
    container_name: service-proxy
    ports:
      - "8080:8080"  # Nominatim
      - "8082:8082"  # Tileserver
      - "8083:8083"  # OSRM
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      tileserver-gl:
        condition: service_healthy
      nominatim:
        condition: service_healthy
      osrm:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - carpool_network
    profiles: ["manual"]

    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 127.0.0.1 8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# to use the dev proxy, add these into your /etc/hosts file:
# 127.0.0.1 nominatim
# 127.0.0.1 tileserver-gl
# 127.0.0.1 osrm

networks:
  carpool_network:
    driver: bridge
