services:
  app:
    image: zodern/meteor
    container_name: carpool-app
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/carpool
      - PORT=3000
    volumes:
      - ./build/app.tar.gz:/bundle/bundle.tar.gz
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: carpool-mongo
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
